### ISSUE TITLE
Importing some monaural recordings fails due to channel number confusion.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#109]
Vesper fails to import some monaural recordings, in particular ones where:
1. The recorder in question has only one microphone output connected to it, but to a channel other than channel zero (as described by the relevant device connections).
2. The recording file name does not indicate a channel number.

An import recordings command that tries to import such a recording raises an exception with the stack trace:

        Traceback (most recent call last):
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\job_runner.py", line 118, in run_job
            complete = command.execute(info)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\import_command.py", line 22, in execute
            return self._importer.execute(context)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\recording_importer.py", line 63, in execute
            self._import_recordings(new_recordings)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\recording_importer.py", line 236, in _import_recordings
            (recorder_channel_num, str(recording)))
        vesper.command.command.CommandExecutionError: Could not find mic output connected to recorder input channel 0 for recording "Floodplain / SM2010811 / start 2017-08-02 02:01:02+00:00 / duration 0.000 h".
        
The import recordings command should be able to infer the channel number of a recording whose file name does not explicitly specify the channel number if the channel number can be inferred from the relevant device connections.

Carrie Voss reported this bug on 2017-08-07.

**Comment by HaroldMills** [comment]
This issue was fixed by 0dc04c3f00426d76614852be72d18637371fb57c.
