### ISSUE TITLE
Recording import fails if station name aliases mention nonexistent station.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#116]
Currently, recording import fails with a KeyError exception if the station name aliases preset for the recording file parser includes as a key the name of a station that does not exist. I think it would be better for the parser to silently ignore the name.

An example of a stack trace generated when the bug is encountered is:

        2017-08-15 15:08:21,521 ERROR    Job raised exception. See traceback below.
        Traceback (most recent call last):
          File 
        "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\mpg_ranch\recording_file_parser.py", line 117, in _create_stations_dict
            station = stations[station_name]
        KeyError: 'Floodplain'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\job_runner.py", line 107, in run_job
            command = _create_command(job_info.command_spec)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\job_runner.py", line 194, in _create_command
            return command_class(command_args)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\import_command.py", line 18, in __init__
            self._importer = _create_importer(importer_spec)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\import_command.py", line 36, in _create_importer
            return cls(arguments)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\recording_importer.py", line 45, in __init__
            self.file_parser = _create_file_parser(spec)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\command\recording_importer.py", line 274, in _create_file_parser
            return parser_class(stations, station_name_aliases)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\mpg_ranch\recording_file_parser.py", line 359, in __init__
            _VesperRecorderFileNameParser(stations, station_name_aliases),
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\mpg_ranch\recording_file_parser.py", line 46, in __init__
            self._stations = _create_stations_dict(stations, station_name_aliases)
          File "C:\Users\Harold\Documents\Code\Python\Vesper\vesper\mpg_ranch\recording_file_parser.py", line 120, in _create_stations_dict
            'Unrecognized station name "{}".'.format(station_name))
        ValueError: Unrecognized station name "Floodplain".

**Comment by HaroldMills** [comment]
Until the bug is fixed, a workaround is to comment out or delete the offending item from the preset.

**Comment by HaroldMills** [comment]
This issue was fixed in 9afb3070c7fb3312a7a2a7bef5159ff42c6ea4d7. The recording importer now ignores unrecognized station names in station name aliases presets. I would like to add a lot more load-time preset validation at some point. It might be good to include station name validation for station name aliases then.
