### ISSUE TITLE
MPG Ranch coarse classifier fails on 32 kHz clips.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#120]
When the MPG Ranch Coarse Classifier 1.0 is run on clips extracted from a Swift recorder, it raises an exception with a message like the one below. I suspect the source of the problem is that the classifier was developed for 22050 Hz clips, while the Swift recorder sample rate is 32000 Hz. Carrie Voss reported this bug.

2017-09-03 11:25:35,260 INFO     Job started for command "classify" with arguments:
    {'annotation_name': 'Classification',
     'classifier': 'MPG Ranch Coarse Classifier 1.0',
     'detectors': ['Old Bird Thrush Detector Redux 1.1'],
     'end_date': datetime.date(2017, 8, 25),
     'start_date': datetime.date(2017, 8, 24),
     'station_mics': ['Bear / 17MPG6']}
2017-09-03 11:25:35,260 INFO     Beginning classification...
2017-09-03 11:25:36,074 INFO     Visited 500 clips...
2017-09-03 11:25:36,135 ERROR    Clip classification failed. The archive has been restored to its state before classification started. See below for exception traceback.
2017-09-03 11:25:36,229 ERROR    Job raised exception. See traceback below.
Traceback (most recent call last):
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\command\job_runner.py", line 118, in run_job
    complete = command.execute(info)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\command\classify_command.py", line 52, in execute
    _classify_clips(clips, classifier)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\command\classify_command.py", line 159, in _classify_clips
    if classifier.annotate(clip):
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\mpg_ranch\coarse_classifier.py", line 43, in annotate
    classification = classifier.classify_clip(clip)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\util\nfc_coarse_classifier.py", line 119, in classify_clip
    segment_classifications, _, _ = self.classify_clip_segments(clip)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\util\nfc_coarse_classifier.py", line 137, in classify_clip_segments
    for s in _generate_segments(sound, segment_length, hop_size)]
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\util\nfc_coarse_classifier.py", line 137, in <listcomp>
    for s in _generate_segments(sound, segment_length, hop_size)]
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\vesper\util\nfc_coarse_classifier.py", line 156, in _classify_segment
    return (self._segment_classifier.predict([features])[0], time)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\sklearn\svm\base.py", line 573, in predict
    y = super(BaseSVC, self).predict(X)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\sklearn\svm\base.py", line 310, in predict
    X = self._validate_for_predict(X)
  File "C:\Users\Acoustics\Miniconda3\envs\vesper\lib\site-packages\sklearn\svm\base.py", line 479, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 133 should be equal to 130, the number of features at training time

**Comment by HaroldMills** [comment]
Fixed in 5291e21e2a01e2ff04aab34aab1d71234e982cfa. The coarse and species classifiers now resample clips to 22050 Hz, the sample rate for which they were designed, when needed.
