### ISSUE TITLE
Recording import crashes on bad .wav file name.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#145]
As of Vesper 0.4.0, the recording importer raises a `CommandExecutionError` exception when it encounters a .wav file whose name it cannot parse. An example stack trace is included below. Instead of raising such an exception, it should log a warning and ignore the file.

Here is an example of an import command and the resulting stack trace for a file named "bobo.wav":

[20/Jul/2018 08:59:57] "POST /import-recordings/ HTTP/1.1" 302 0
[20/Jul/2018 08:59:57] "GET /jobs/244/ HTTP/1.1" 200 5525
2018-07-20 08:59:57,975 INFO     Job started for command "import" with arguments:
2018-07-20 08:59:57,976 INFO         {
2018-07-20 08:59:57,976 INFO             "importer": {
2018-07-20 08:59:57,976 INFO                 "name": "Recording Importer",
2018-07-20 08:59:57,976 INFO                 "arguments": {
2018-07-20 08:59:57,976 INFO                     "paths": [
2018-07-20 08:59:57,976 INFO                         "/Users/Harold/Desktop/NFC/Data/harold/2018 Harold Archive/Recordings"
2018-07-20 08:59:57,977 INFO                     ],
2018-07-20 08:59:57,977 INFO                     "recursive": false,
2018-07-20 08:59:57,977 INFO                     "recording_file_parser": {
2018-07-20 08:59:57,977 INFO                         "name": "MPG Ranch Recording File Parser",
2018-07-20 08:59:57,977 INFO                         "arguments": {
2018-07-20 08:59:57,977 INFO                             "station_name_aliases_preset": "Station Name Aliases"
2018-07-20 08:59:57,977 INFO                         }
2018-07-20 08:59:57,977 INFO                     }
2018-07-20 08:59:57,977 INFO                 }
2018-07-20 08:59:57,977 INFO             }
2018-07-20 08:59:57,977 INFO         }
2018-07-20 08:59:58,043 ERROR    Recording import failed with an exception.
The exception message was:
    Error parsing recording file "/Users/Harold/Desktop/NFC/Data/harold/2018 Harold Archive/Recordings/bobo.wav": Could not parse file name.
The archive was not modified.
See below for exception traceback.
2018-07-20 08:59:58,050 ERROR    Job raised exception. See traceback below.
Traceback (most recent call last):
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 193, in _parse_recording_file
    file = self.file_parser.parse_file(str(file_path))
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/mpg_ranch/recording_file_parser.py", line 525, in parse_file
    self._parse_file_name(file_path)
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/mpg_ranch/recording_file_parser.py", line 554, in _parse_file_name
    raise ValueError('Could not parse file name.')
ValueError: Could not parse file name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/import_command.py", line 22, in execute
    return self._importer.execute(context)
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 58, in execute
    recordings = self._get_recordings()
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 85, in _get_recordings
    self._get_path_recording_files(path) for path in self.paths))
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 85, in <genexpr>
    self._get_path_recording_files(path) for path in self.paths))
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 92, in _get_path_recording_files
    return self._get_dir_recording_files(path)
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 107, in _get_dir_recording_files
    file = self._get_recording_file(Path(file_path))
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 126, in _get_recording_file
    file = self._parse_recording_file(abs_path)
  File "/Users/harold/Documents/Code/Python/Vesper/vesper/command/recording_importer.py", line 198, in _parse_recording_file
    file_path, str(e)))
vesper.command.command.CommandExecutionError: Error parsing recording file "/Users/Harold/Desktop/NFC/Data/harold/2018 Harold Archive/Recordings/bobo.wav": Could not parse file name.

**Comment by HaroldMills** [comment]
After further consideration, I've realized that this behavior was intentional, and have decided to keep it. The idea is that an entire import should fail if there's a problem with any of the files, to help draw attention to the problem. It would be too easy for a user to miss a just a warning.
