### ISSUE TITLE
Unable to detect

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#160]
I am unable to use the Detect feature in 0.4.8. Here is the printout:

```sh
[19/Mar/2020 15:14:18] "GET /static/vesper/view/detect-form.css HTTP/1.1" 304 0
Exception ignored in: <module 'threading' from '//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 1351, in _after_fork
    thread._reset_internal_locks(False)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 805, in _reset_internal_locks
    self._started._reset_internal_locks()
[19/Mar/2020 15:14:27] "POST /detect/ HTTP/1.1" 302 0
AttributeError: 'bool' object has no attribute '_reset_internal_locks'
[19/Mar/2020 15:14:28] "GET /jobs/96/ HTTP/1.1" 200 6979
2020-03-19 15:14:28,149 INFO     Job started for command "detect" with arguments:
2020-03-19 15:14:28,150 INFO         {
2020-03-19 15:14:28,151 INFO             "detectors": [
2020-03-19 15:14:28,151 INFO                 "Old Bird Tseep Detector Redux 1.1"
2020-03-19 15:14:28,154 INFO             ],
2020-03-19 15:14:28,154 INFO             "stations": [
2020-03-19 15:14:28,154 INFO                 "MSGR"
2020-03-19 15:14:28,155 INFO             ],
2020-03-19 15:14:28,155 INFO             "start_date": "2020-03-18",
2020-03-19 15:14:28,155 INFO             "end_date": "2020-03-30",
2020-03-19 15:14:28,155 INFO             "schedule": "",
2020-03-19 15:14:28,155 INFO             "defer_clip_creation": false
2020-03-19 15:14:28,155 INFO         }
2020-03-19 15:14:28,169 INFO     This command will process recordings for 1 station-night.
2020-03-19 15:14:28,169 INFO     Processing recordings for station-night 1 of 1 - "MSGR 2020-03-18"...
2020-03-19 15:14:28,171 INFO         Processing recording 1 of 1 - "MSGR / PC / start 2020-03-19 00:30:00+00:00 / duration 9.000 h"...
2020-03-19 15:14:28,174 INFO             Running detector on file "/Volumes/Ultan/vesper/msgr-vesper-archive/Recordings/MSGR_2020-03-19_00.30.00_Z.wav"...
2020-03-19 15:14:28,451 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 866, in _create_clips
    creating_processor=detector_model
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 172, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 152, in execute
    self._run_other_detectors(other_detectors, recordings)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 352, in _run_other_detectors
    detector_models, file_, recording_intervals)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 438, in _run_other_detectors_on_file
    detector_models, file_, abs_path, reader, interval)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 467, in _run_other_detectors_on_file_interval
    detector.detect(channel_samples)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 278, in detect
    self._notify_listener(clips)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 322, in _notify_listener
    self._listener.process_clip(start_index, length)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 784, in process_clip
    self._create_clips(threshold)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 895, in _create_clips
    station.name, mic_output.name,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/django/app/models.py", line 187, in name
    return self.device.name + ' ' + self.local_name
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 186, in __get__
    rel_obj = self.get_object(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 153, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/base/base.py", line 449, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by HaroldMills** [comment]
It looks like you probably tried to run a detector a second time on a recording. This attempts to create duplicate clips, which the database does not allow (hence the initial IntegrityError exception). The detection job is not supposed to fail in this case, as it did for you, but rather log error messages indicating that clips could not be created. Unfortunately, however, there was a bug in the detect command's error handling code that caused the TransactionManagementError exception to be raised. I have fixed the bug (see e1ff38e97ea10a50641813aaf0075e34a5c4326d) and the fix will appear in Vesper 0.4.9. Thank you for bringing this problem to my attention!

**Comment by RichardLitt** [comment]
Glad I could help! That's why I'm opening issues; apologies if I seem to be going overboard with these! Even when I miss something I obvious, I hope that it could be seen as a UX issue for naïve users. 

One thing about the unique constraint: right now, it runs through the entire file, trying each clip. Would it make sense to figure out that it's already looked at a file, and skip detecting each clip? That might speed up the detect process for large files which have already been detected.

**Comment by RichardLitt** [comment]
While it does happen for detecting a second time on recordings, this means that each night, I need to change the dates that I select for detection, in order to make sure that none of the past dates which I've already detected are included. This adds an extra step for me, each time. Can we skip past files, instead of having the command fail if there are any duplicated events? 

Is there a way to use 0.4.9~beta before it is released?

**Comment by HaroldMills** [comment]
This relates to a long-standing issue (see issue #76, from 2016): it would be good for Vesper to know more about a user's workflow so it could keep track of which processing steps have been completed for which recordings. Then Vesper could display some sort of representation of that information to help guide the user's actions, or use that information to perform many steps of the workflow automatically. For example, in your case you might be able to press a button and have Vesper figure out which recordings in your recording directory had not yet been imported, import them, run certain detectors on them, and then run certain classifiers on the resulting clips. I may or may not be able to address that issue this year, depending on such things as the time I have available to work on Vesper and funders' priorities. Unfortunately, in the interim users must keep track of which recordings they've processed themselves. For my own use I have found the clip calendar helpful for this: if I ever lose track of which recordings from a particular station I've processed with a particular detector, I look at a clip calendar for all clips produced by that detector for that station. On that calendar, the dates for which there are clips are the dates for which I ran the detector (unless the detector produced no clips for a recording, but that is unusual). Other users maintain a spreadsheet in which they record which of their workflow steps they have completed for which recordings.

Since Vesper is open source and available in a public GitHub repository, you can obtain its source code from there as of any Git commit to run yourself.

**Comment by HaroldMills** [comment]
You'll need to create a Python environment for your non-release version of Vesper and run Vesper using that environment. Vesper's [setup.py](https://github.com/HaroldMills/Vesper/blob/master/setup.py) has some comments near the top that I use to help me keep track of how to do various Vesper package building tasks, including creating a development environment. Search for "To create a conda environment for Vesper development". But note that the procedure changes fairly frequently, as both Vesper and its dependencies evolve.

**Comment by RichardLitt** [comment]
I no longer have this issue. Closing this as it's already a known bug.
