### ISSUE TITLE
Possible issue with renaming files

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#162]
I renamed two files, and then re-added them without deleting them. Importing worked fine, but on trying to detect, I got these errors. I am going to delete the recordings on these days and then try importing them again. 

```
09:38 /Volumes/Erebus/msgr-vesper-archive (master) * 🦉 vesper_admin runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 23, 2020 - 09:38:28
Django version 3.0.4, using settings 'vesper.django.project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
WARNING:tensorflow:From //anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/mpg_ranch/nfc_coarse_classifier_3_0/dataset_utils.py:25: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

ERROR:root:Preset manager could not read preset file "/Volumes/Erebus/msgr-vesper-archive/Presets/Clip Album Commands/._Calls.yaml".
ERROR:root:Preset manager could not read preset file "/Volumes/Erebus/msgr-vesper-archive/Presets/Clip Album Commands/._Coarse.yaml".
ERROR:root:Preset manager could not read preset file "/Volumes/Erebus/msgr-vesper-archive/Presets/Clip Album Settings/._Resizing Clips, Labels Below.yaml".
ERROR:root:Preset manager could not read preset file "/Volumes/Erebus/msgr-vesper-archive/Presets/Detection Schedule/._Ithaca 2019.yaml".
ERROR:root:Preset manager could not read preset file "/Volumes/Erebus/msgr-vesper-archive/Presets/Station Name Aliases/._Station Name Aliases.yaml".
[23/Mar/2020 09:38:34] "GET /detect/ HTTP/1.1" 200 11348
Exception ignored in: <module 'threading' from '//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 1351, in _after_fork
    thread._reset_internal_locks(False)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 805, in _reset_internal_locks
    self._started._reset_internal_locks()
AttributeError: 'bool' object has no attribute '_reset_internal_locks'
[23/Mar/2020 09:38:42] "POST /detect/ HTTP/1.1" 302 0
INFO:root:Job started for command "detect" with arguments:
INFO:root:    {
INFO:root:        "detectors": [
INFO:root:            "Old Bird Thrush Detector Redux 1.1"
INFO:root:        ],
INFO:root:        "stations": [
INFO:root:            "MSGR"
INFO:root:        ],
INFO:root:        "start_date": "2020-03-20",
INFO:root:        "end_date": "2020-03-30",
INFO:root:        "schedule": "",
INFO:root:        "defer_clip_creation": false
INFO:root:    }
2020-03-23 09:38:42,742 INFO     Job started for command "detect" with arguments:
2020-03-23 09:38:42,743 INFO         {
2020-03-23 09:38:42,744 INFO             "detectors": [
2020-03-23 09:38:42,744 INFO                 "Old Bird Thrush Detector Redux 1.1"
2020-03-23 09:38:42,744 INFO             ],
2020-03-23 09:38:42,744 INFO             "stations": [
2020-03-23 09:38:42,744 INFO                 "MSGR"
2020-03-23 09:38:42,744 INFO             ],
2020-03-23 09:38:42,744 INFO             "start_date": "2020-03-20",
2020-03-23 09:38:42,744 INFO             "end_date": "2020-03-30",
2020-03-23 09:38:42,744 INFO             "schedule": "",
2020-03-23 09:38:42,744 INFO             "defer_clip_creation": false
2020-03-23 09:38:42,744 INFO         }
INFO:root:This command will process recordings for 3 station-nights.
INFO:root:Processing recordings for station-night 1 of 3 - "MSGR 2020-03-20"...
2020-03-23 09:38:42,760 INFO     This command will process recordings for 3 station-nights.
2020-03-23 09:38:42,760 INFO     Processing recordings for station-night 1 of 3 - "MSGR 2020-03-20"...
INFO:root:    Processing recording 1 of 3 - "MSGR / PC / start 2020-03-21 00:15:17+00:00 / duration 1.587 h"...
2020-03-23 09:38:42,763 INFO         Processing recording 1 of 3 - "MSGR / PC / start 2020-03-21 00:15:17+00:00 / duration 1.587 h"...
ERROR:root:        Recording file path "MSGR_2020-03-21_00.15.17_Z.wav" could not be made absolute since it is not in the recording directory "/Volumes/Erebus/msgr-vesper-archive/Recordings".
INFO:root:    Processing recording 2 of 3 - "MSGR / PC / start 2020-03-21 01:00:28+00:00 / duration 14.293 h"...
2020-03-23 09:38:42,766 ERROR            Recording file path "MSGR_2020-03-21_00.15.17_Z.wav" could not be made absolute since it is not in the recording directory "/Volumes/Erebus/msgr-vesper-archive/Recordings".
2020-03-23 09:38:42,768 INFO         Processing recording 2 of 3 - "MSGR / PC / start 2020-03-21 01:00:28+00:00 / duration 14.293 h"...
INFO:root:        Running detector on file "/Volumes/Erebus/msgr-vesper-archive/Recordings/MSGR_2020-03-21_01.00.28_Z.wav"...
2020-03-23 09:38:42,771 INFO             Running detector on file "/Volumes/Erebus/msgr-vesper-archive/Recordings/MSGR_2020-03-21_01.00.28_Z.wav"...
[23/Mar/2020 09:38:42] "GET /jobs/121/ HTTP/1.1" 200 8767
ERROR:root:Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 866, in _create_clips
    creating_processor=detector_model
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 172, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 152, in execute
    self._run_other_detectors(other_detectors, recordings)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 352, in _run_other_detectors
    detector_models, file_, recording_intervals)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 438, in _run_other_detectors_on_file
    detector_models, file_, abs_path, reader, interval)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 467, in _run_other_detectors_on_file_interval
    detector.detect(channel_samples)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 278, in detect
    self._notify_listener(clips)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 322, in _notify_listener
    self._listener.process_clip(start_index, length)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 784, in process_clip
    self._create_clips(threshold)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 895, in _create_clips
    station.name, mic_output.name,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/django/app/models.py", line 187, in name
    return self.device.name + ' ' + self.local_name
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 186, in __get__
    rel_obj = self.get_object(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 153, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/base/base.py", line 449, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

2020-03-23 09:38:42,978 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 866, in _create_clips
    creating_processor=detector_model
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: vesper_clip.recording_channel_id, vesper_clip.start_time, vesper_clip.creating_processor_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 172, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 152, in execute
    self._run_other_detectors(other_detectors, recordings)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 352, in _run_other_detectors
    detector_models, file_, recording_intervals)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 438, in _run_other_detectors_on_file
    detector_models, file_, abs_path, reader, interval)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 467, in _run_other_detectors_on_file_interval
    detector.detect(channel_samples)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 278, in detect
    self._notify_listener(clips)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/old_bird/old_bird_detector_redux_1_1.py", line 322, in _notify_listener
    self._listener.process_clip(start_index, length)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 784, in process_clip
    self._create_clips(threshold)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/detect_command.py", line 895, in _create_clips
    station.name, mic_output.name,
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/django/app/models.py", line 187, in name
    return self.device.name + ' ' + self.local_name
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 186, in __get__
    rel_obj = self.get_object(instance)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 153, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "//anaconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/django/db/backends/base/base.py", line 449, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

```

**Comment by RichardLitt** [comment]
I was able to detect and classify files once I deleted and reimported the files. Still, I think the error could be made clearer. Or perhaps this flow should be in the FAQ?

**Comment by HaroldMills** [comment]
Vesper is not supposed to allow you to import the same recording twice, even if you change the names of its files. I just imported a recording, changed the name of its file, and then attempted to reimport it, and Vesper realized that the station, recorder, and start time of the recording were the same as that of an existing recording and did not import it. Could you please send me a short list of steps that will reproduce the problem you saw?

**Comment by RichardLitt** [comment]
Did you change the start time? I believe that is what I was doing when I renamed the files, although I can no longer remember accurately enough to reproduce the problem exactly. It might be best to just close this; we can reopen if it happens again.

**Comment by HaroldMills** [comment]
Closing this issue, as @RichardLitt suggested.
