### ISSUE TITLE
Unable to import files

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#176]
I'm trying to get Vesper set up for what is now an older station, and I'm having issues importing files. 

Here are my logs. I've tried migrating, copying the code from my working station, and looking through the .yaml files for anything about what "could not find recorder" means. Any ideas? 

```
(vesper-0.4.8) ➜  nbnc-test-public git:(master) ✗ vesper_admin runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 24, 2020 - 19:18:03
Django version 3.0.6, using settings 'vesper.django.project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Sep/2020 19:18:05] "GET / HTTP/1.1" 302 0
[24/Sep/2020 19:18:05] "GET /clip-calendar/ HTTP/1.1" 200 19515
[24/Sep/2020 19:18:07] "GET /import-recordings/ HTTP/1.1" 302 0
[24/Sep/2020 19:18:07] "GET /login/?next=/import-recordings/ HTTP/1.1" 200 2723
[24/Sep/2020 19:18:08] "GET /static/vesper/command-form.css HTTP/1.1" 404 1695
[24/Sep/2020 19:18:08] "GET /static/vesper/command-form.css HTTP/1.1" 404 1695
[24/Sep/2020 19:18:12] "POST /login/ HTTP/1.1" 302 0
[24/Sep/2020 19:18:12] "GET /import-recordings/ HTTP/1.1" 200 8431
Exception ignored in: <module 'threading' from '/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 1351, in _after_fork
    thread._reset_internal_locks(False)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/threading.py", line 805, in _reset_internal_locks
    self._started._reset_internal_locks()
AttributeError: 'bool' object has no attribute '_reset_internal_locks'
[24/Sep/2020 19:18:14] "POST /import-recordings/ HTTP/1.1" 302 0
[24/Sep/2020 19:18:14] "GET /jobs/12/ HTTP/1.1" 200 7107
2020-09-24 19:18:19,609 WARNING  From /Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/mpg_ranch/nfc_coarse_classifier_3_0/dataset_utils.py:25: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
2020-09-24 19:18:20,225 WARNING  Preset manager encountered directory for unrecognized preset type "Classification Commands" at "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Classification Commands".
2020-09-24 19:18:20,246 ERROR    Preset manager could not read preset file "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Clip Album Commands/._Calls.yaml".
2020-09-24 19:18:20,256 ERROR    Preset manager could not read preset file "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Clip Album Commands/._Coarse.yaml".
2020-09-24 19:18:20,268 ERROR    Preset manager could not read preset file "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Clip Album Settings/._Resizing Clips, Labels Below.yaml".
2020-09-24 19:18:20,273 ERROR    Preset manager could not read preset file "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Detection Schedule/._Ithaca 2019.yaml".
2020-09-24 19:18:20,276 ERROR    Preset manager could not read preset file "/Volumes/Erebus/NBNC/nbnc-test-public/Presets/Station Name Aliases/._Station Name Aliases.yaml".
2020-09-24 19:18:20,276 INFO     Job started for command "import" with arguments:
2020-09-24 19:18:20,276 INFO         {
2020-09-24 19:18:20,276 INFO             "importer": {
2020-09-24 19:18:20,276 INFO                 "name": "Recording Importer",
2020-09-24 19:18:20,276 INFO                 "arguments": {
2020-09-24 19:18:20,276 INFO                     "paths": [
2020-09-24 19:18:20,276 INFO                         "/Volumes/Erebus/NBNC/nbnc-test-public/Recordings"
2020-09-24 19:18:20,276 INFO                     ],
2020-09-24 19:18:20,276 INFO                     "recursive": false,
2020-09-24 19:18:20,276 INFO                     "recording_file_parser": {
2020-09-24 19:18:20,276 INFO                         "name": "MPG Ranch Recording File Parser",
2020-09-24 19:18:20,276 INFO                         "arguments": {
2020-09-24 19:18:20,276 INFO                             "station_name_aliases_preset": "Station Name Aliases"
2020-09-24 19:18:20,276 INFO                         }
2020-09-24 19:18:20,276 INFO                     }
2020-09-24 19:18:20,276 INFO                 }
2020-09-24 19:18:20,276 INFO             }
2020-09-24 19:18:20,276 INFO         }
2020-09-24 19:18:20,292 ERROR    Recording import failed with an exception.
The exception message was:
    Could not find recorder for recording file "/Volumes/Erebus/NBNC/nbnc-test-public/Recordings/NBNC_2020-09-19_00.00.00_Z.wav".
The archive was not modified.
See below for exception traceback.
2020-09-24 19:18:20,297 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/import_command.py", line 22, in execute
    return self._importer.execute(context)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 57, in execute
    recordings = self._get_recordings()
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 84, in _get_recordings
    self._get_path_recording_files(path) for path in self.paths))
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 84, in <genexpr>
    self._get_path_recording_files(path) for path in self.paths))
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 91, in _get_path_recording_files
    return self._get_dir_recording_files(path)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 106, in _get_dir_recording_files
    file = self._get_recording_file(Path(file_path))
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 125, in _get_recording_file
    file = self._parse_recording_file(abs_path)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 200, in _parse_recording_file
    file.recorder = _get_recorder(file)
  File "/Users/richard/miniconda3/envs/vesper-0.4.8/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 342, in _get_recorder
    file.path))
vesper.command.command.CommandExecutionError: Could not find recorder for recording file "/Volumes/Erebus/NBNC/nbnc-test-public/Recordings/NBNC_2020-09-19_00.00.00_Z.wav".
```

**Comment by RichardLitt** [comment]
Looks like I failed to import the .yaml files. Not sure why this was needed for an old archive I was just updating for the season, but it may have been the date range. Fixed now.
