### ISSUE TITLE
Failed to load Tensorflow

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#179]
I've recently installed Vesper on a Windows machine, and I'm having issues looking at clips. Any idea? Here's the error I am getting. 

``` 
[30/Jan/2021 23:03:36] "GET /night/?station_mic=MSGR%20%2F%2021c&detector=Old%20Bird%20Tseep%20Detector%20Redux%201.1&classification=Call*&date=2020-08-20 HTTP/1.1" 500 265433
Internal Server Error: /night/
Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\django\app\views.py", line 1649, in night
    preset_manager.instance.reload_presets()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\singleton.py", line 35, in instance
    self._instance = self._instance_factory()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\singletons.py", line 174, in _create_preset_manager
    preset_types = extension_manager.instance.get_extensions('Preset')
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 55, in get_extensions
    self._load_extensions_if_needed()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 65, in _load_extensions_if_needed
    for type_name, module_class_names in spec.items())
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 65, in <genexpr>
    for type_name, module_class_names in spec.items())
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 69, in _load_extension_classes
    return [_load_extension_class(name) for name in module_class_names]
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 69, in <listcomp>
    return [_load_extension_class(name) for name in module_class_names]
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\util\extension_manager.py", line 74, in _load_extension_class
    module = importlib.import_module(module_name)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\vesper\mpg_ranch\nfc_coarse_classifier_3_0\classifier.py", line 20, in <module>
    import tensorflow as tf
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[30/Jan/2021 23:03:36] "GET /night/?station_mic=MSGR%20%2F%2021c&detector=Old%20Bird%20Tseep%20Detector%20Redux%201.1&classification=Call*&date=2020-08-20 HTTP/1.1" 500 266521
Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[30/Jan/2021 23:03:36] "GET /night/?station_mic=MSGR%20%2F%2021c&detector=Old%20Bird%20Tseep%20Detector%20Redux%201.1&classification=Call*&date=2020-08-20 HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50547)
Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\servers\basehttp.py", line 119, in handle_error
    super().handle_error()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\socketserver.py", line 724, in __init__
    self.handle()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\servers\basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\site-packages\django\core\servers\basehttp.py", line 114, in close
    super().close()
  File "c:\users\richard\miniconda3\envs\vesper-0.4.8\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

**Comment by HaroldMills** [comment]
I'm not sure what would cause the problem you're seeing. I just installed Vesper 0.4.8 on Windows 10 and am able to look at night clip albums. I would suggest re-installing Vesper, making sure you use the [most recent installation instructions](https://vesper.readthedocs.io/en/latest/installation.html) (those do change occasionally, even for a given Vesper version). If the problem persists, please send me a list of the Python packages in your environment (from the `conda list` command), and I'll check to see if they look reasonable.

**Comment by RichardLitt** [comment]
Thanks @HaroldMills. I'll try that and get back to you on how it goes.

**Comment by HaroldMills** [comment]
@RichardLitt, is this issue now resolved?

**Comment by RichardLitt** [comment]
I'm not using Windows at the moment - I manually transfer everything over to my OSX machine. Will reopen if I need to. Thanks, Harold.
