### ISSUE TITLE
Allow different stations to use the same recorders

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#195]
I move my recorders around and create temporary NFC stations. However, I'm unable to use the same equipment in multiple stations. 

Metadata:
```yaml
device_models:

    - name: PC
      type: Audio Recorder
      manufacturer: Various
      model: PC
      description: Personal computer as an audio recorder.
      num_inputs: 2

    - name: 21c
      type: Microphone
      manufacturer: Old Bird, Inc.
      model: 21c
      description: Old Bird bucket microphone.
      num_outputs: 1

devices:

    - name: PC
      model: PC
      serial_number: 0
      description: Recorder used at all stations.

    - name: 21c
      model: 21c
      serial_number: 0
      description: Microphone used at all station.
```

Error
```
2022-03-13 05:02:57,735 INFO     Job started for command "import" with arguments:
2022-03-13 05:02:57,735 INFO         {
2022-03-13 05:02:57,735 INFO             "importer": {
2022-03-13 05:02:57,736 INFO                 "name": "Metadata Importer",
2022-03-13 05:02:57,736 INFO                 "arguments": {
2022-03-13 05:02:57,736 INFO                     "metadata": {
2022-03-13 05:02:57,736 INFO                         "station_devices": [
2022-03-13 05:02:57,737 INFO                             {
2022-03-13 05:02:57,737 INFO                                 "station": "Friendship",
2022-03-13 05:02:57,737 INFO                                 "start_time": "2021-09-18",
2022-03-13 05:02:57,737 INFO                                 "end_time": "2021-09-22",
2022-03-13 05:02:57,738 INFO                                 "devices": [
2022-03-13 05:02:57,738 INFO                                     "PC",
2022-03-13 05:02:57,738 INFO                                     "21c 0"
2022-03-13 05:02:57,738 INFO                                 ],
2022-03-13 05:02:57,738 INFO                                 "connections": [
2022-03-13 05:02:57,739 INFO                                     {
2022-03-13 05:02:57,739 INFO                                         "output": "21c Output",
2022-03-13 05:02:57,739 INFO                                         "input": "PC Input 0"
2022-03-13 05:02:57,739 INFO                                     }
2022-03-13 05:02:57,739 INFO                                 ]
2022-03-13 05:02:57,739 INFO                             },
2022-03-13 05:02:57,739 INFO                             {
2022-03-13 05:02:57,739 INFO                                 "station": "Stannard",
2022-03-13 05:02:57,740 INFO                                 "start_time": "2021-04-13",
2022-03-13 05:02:57,740 INFO                                 "end_time": "2021-04-14",
2022-03-13 05:02:57,740 INFO                                 "devices": [
2022-03-13 05:02:57,740 INFO                                     "PC",
2022-03-13 05:02:57,740 INFO                                     "21c 0"
2022-03-13 05:02:57,741 INFO                                 ],
2022-03-13 05:02:57,741 INFO                                 "connections": [
2022-03-13 05:02:57,741 INFO                                     {
2022-03-13 05:02:57,741 INFO                                         "output": "21c Output",
2022-03-13 05:02:57,741 INFO                                         "input": "PC Input 0"
2022-03-13 05:02:57,741 INFO                                     }
2022-03-13 05:02:57,741 INFO                                 ]
2022-03-13 05:02:57,741 INFO                             },
2022-03-13 05:02:57,742 INFO                             {
2022-03-13 05:02:57,742 INFO                                 "station": "Bennington",
2022-03-13 05:02:57,742 INFO                                 "start_time": "2021-04-24",
2022-03-13 05:02:57,742 INFO                                 "end_time": "2021-04-25",
2022-03-13 05:02:57,743 INFO                                 "devices": [
2022-03-13 05:02:57,743 INFO                                     "PC",
2022-03-13 05:02:57,743 INFO                                     "21c 0"
2022-03-13 05:02:57,743 INFO                                 ],
2022-03-13 05:02:57,743 INFO                                 "connections": [
2022-03-13 05:02:57,744 INFO                                     {
2022-03-13 05:02:57,744 INFO                                         "output": "21c Output",
2022-03-13 05:02:57,744 INFO                                         "input": "PC Input 0"
2022-03-13 05:02:57,744 INFO                                     }
2022-03-13 05:02:57,744 INFO                                 ]
2022-03-13 05:02:57,745 INFO                             },
2022-03-13 05:02:57,745 INFO                             {
2022-03-13 05:02:57,745 INFO                                 "station": "White Crest",
2022-03-13 05:02:57,745 INFO                                 "start_time": "2021-08-14",
2022-03-13 05:02:57,745 INFO                                 "end_time": "2021-08-15",
2022-03-13 05:02:57,745 INFO                                 "devices": [
2022-03-13 05:02:57,745 INFO                                     "PC",
2022-03-13 05:02:57,746 INFO                                     "21c 0"
2022-03-13 05:02:57,746 INFO                                 ],
2022-03-13 05:02:57,746 INFO                                 "connections": [
2022-03-13 05:02:57,746 INFO                                     {
2022-03-13 05:02:57,746 INFO                                         "output": "21c Output",
2022-03-13 05:02:57,746 INFO                                         "input": "PC Input 0"
2022-03-13 05:02:57,747 INFO                                     }
2022-03-13 05:02:57,747 INFO                                 ]
2022-03-13 05:02:57,747 INFO                             },
2022-03-13 05:02:57,747 INFO                             {
2022-03-13 05:02:57,747 INFO                                 "station": "Berlin Pond",
2022-03-13 05:02:57,747 INFO                                 "start_time": "2021-04-07",
2022-03-13 05:02:57,748 INFO                                 "end_time": "2021-04-08",
2022-03-13 05:02:57,748 INFO                                 "devices": [
2022-03-13 05:02:57,748 INFO                                     "PC",
2022-03-13 05:02:57,748 INFO                                     "21c 0"
2022-03-13 05:02:57,748 INFO                                 ],
2022-03-13 05:02:57,748 INFO                                 "connections": [
2022-03-13 05:02:57,749 INFO                                     {
2022-03-13 05:02:57,749 INFO                                         "output": "21c Output",
2022-03-13 05:02:57,749 INFO                                         "input": "PC Input 0"
2022-03-13 05:02:57,749 INFO                                     }
2022-03-13 05:02:57,749 INFO                                 ]
2022-03-13 05:02:57,749 INFO                             }
2022-03-13 05:02:57,750 INFO                         ]
2022-03-13 05:02:57,750 INFO                     }
2022-03-13 05:02:57,750 INFO                 }
2022-03-13 05:02:57,750 INFO             }
2022-03-13 05:02:57,750 INFO         }
2022-03-13 05:02:57,779 INFO     Adding station "Friendship" device "PC" from 2021-09-18 04:00:00+00:00 to 2021-09-22 04:00:00+00:00"...
2022-03-13 05:02:57,780 ERROR    Metadata import failed with an exception. Database has been restored to its state before the import. See below for exception traceback.
2022-03-13 05:02:57,788 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: vesper_station_device.station_id, vesper_station_device.device_id, vesper_station_device.start_time, vesper_station_device.end_time

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/vesper/command/job_runner.py", line 144, in run_job
    complete = command.execute(info)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/vesper/command/import_command.py", line 22, in execute
    return self._importer.execute(context)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/vesper/command/metadata_importer.py", line 117, in execute
    self._add_station_devices()
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/vesper/command/metadata_importer.py", line 326, in _add_station_devices
    self._add_station_device(
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/vesper/command/metadata_importer.py", line 371, in _add_station_device
    StationDevice.objects.create(
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/richard/miniconda3/envs/vesper-920f23c/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: vesper_station_device.station_id, vesper_station_device.device_id, vesper_station_device.start_time, vesper_station_device.end_time
```

**Comment by HaroldMills** [comment]
From the job log, it looks like the very first station device interval, concerning station "Friendship" device "PC" from midnight on 2021-09-18 to midnight on 2021-09-22, probably overlaps with an existing vesper_station_device archive database row. Is that the case?
