### ISSUE TITLE
Unable to run birdvox

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#200]
Ran into this problem today. Not sure if this is a bug or support! 

```sh
2022-07-14 11:58:21,439 INFO     Job started for command "detect" with arguments:
2022-07-14 11:58:21,439 INFO         {
2022-07-14 11:58:21,440 INFO             "detectors": [
2022-07-14 11:58:21,440 INFO                 "BirdVoxDetect 0.6.0 AT 50"
2022-07-14 11:58:21,441 INFO             ],
2022-07-14 11:58:21,442 INFO             "stations": [
2022-07-14 11:58:21,443 INFO                 "Bridge of Oich"
2022-07-14 11:58:21,443 INFO             ],
2022-07-14 11:58:21,444 INFO             "start_date": "2022-04-16",
2022-07-14 11:58:21,444 INFO             "end_date": "2022-04-18",
2022-07-14 11:58:21,445 INFO             "schedule": "-----",
2022-07-14 11:58:21,446 INFO             "defer_clip_creation": false
2022-07-14 11:58:21,447 INFO         }
2022-07-14 11:58:21,459 INFO     This command will process recordings for 1 station-night.
2022-07-14 11:58:21,459 INFO     Processing recordings for station-night 1 of 1 - "Bridge of Oich 2022-04-16"...
2022-07-14 11:58:21,461 INFO         Processing recording 1 of 11 - "Bridge of Oich / PC / start 2022-04-16 20:30:00+00:00 / duration 0.499 h"...
2022-07-14 11:58:21,464 INFO             Running detector on file "/Users/richard/Sound/nfc-22-04-16-oich/Recordings/Bridge of Oich_2022-04-16_20.30.00_Z.wav"...
2022-07-14 11:58:22,313 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/birdvox/detectors.py", line 132, in complete_detection
    module_name, args, environment_name)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/util/conda_utils.py", line 21, in run_python_script
    interpreter_path, env_vars = _get_run_info(environment_name)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/util/conda_utils.py", line 57, in _get_run_info
    _split_interpreter_path(current_interpreter_path)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/util/conda_utils.py", line 90, in _split_interpreter_path
    f'Python interpreter path "{path}" does not include expected '
ValueError: Python interpreter path "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7" does not include expected Miniconda or Anaconda "envs" directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/job_runner.py", line 144, in run_job
    complete = command.execute(info)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/detect_command.py", line 146, in execute
    self._run_other_detectors(other_detectors, recordings)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/detect_command.py", line 344, in _run_other_detectors
    detector_models, file_, recording_intervals)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/detect_command.py", line 434, in _run_other_detectors_on_file
    detector_models, file_, abs_path, reader, interval)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/detect_command.py", line 467, in _run_other_detectors_on_file_interval
    detector.complete_detection()
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/birdvox/detectors.py", line 136, in complete_detection
    f'Could not run {self.extension_name} in Conda '
vesper.birdvox.detectors.DetectorError: Could not run BirdVoxDetect 0.6.0 AT 50 in Conda environment "birdvoxdetect-0.6.0". Error message was: Python interpreter path "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7" does not include expected Miniconda or Anaconda "envs" directory.
```

And these conda environments:

```sh
nfc-22-04-16-oich $ conda activate birdvoxdetect-0.6.0
(birdvoxdetect-0.6.0) ➜  nfc-22-04-16-oich $ conda activate vesper-0.4.13
(vesper-0.4.13) ➜  nfc-22-04-16-oich $ vesper_admin runserver
```

**Comment by HaroldMills** [comment]
It looks like you're running Vesper using a Python interpreter (/Users/richard/Library/Python/3.7) that is not installed in a Conda environment. Both Vesper and BirdVoxDetect need to be installed in Conda environments for Vesper to be able to find BirdVoxDetect.

**Comment by RichardLitt** [comment]
Thanks @HaroldMills - that sounds like it might be the issue to me, too. I'll take a look at it and let you know. Closing this for now.

**Comment by RichardLitt** [comment]
Hmm. Having issues finding `vesper_birdvox`. I've tried `pip install vesper_birdvox`. 

```
2022-08-12 10:46:59,510 INFO     Job started for command "detect" with arguments:
2022-08-12 10:46:59,510 INFO         {
2022-08-12 10:46:59,511 INFO             "detectors": [
2022-08-12 10:46:59,511 INFO                 "BirdVoxDetect 0.6.0 FT 50"
2022-08-12 10:46:59,511 INFO             ],
2022-08-12 10:46:59,512 INFO             "stations": [
2022-08-12 10:46:59,512 INFO                 "MSGR"
2022-08-12 10:46:59,512 INFO             ],
2022-08-12 10:46:59,513 INFO             "start_date": "2022-08-01",
2022-08-12 10:46:59,513 INFO             "end_date": "2022-09-01",
2022-08-12 10:46:59,513 INFO             "schedule": "-----",
2022-08-12 10:46:59,513 INFO             "defer_clip_creation": false
2022-08-12 10:46:59,513 INFO         }
2022-08-12 10:46:59,539 INFO     This command will process recordings for 5 station-nights.
2022-08-12 10:46:59,539 INFO     Processing recordings for station-night 1 of 5 - "MSGR 2022-08-06"...
2022-08-12 10:46:59,540 INFO         Processing recording 1 of 2 - "MSGR / PC / start 2022-08-07 03:47:07+00:00 / duration 0.033 h"...
2022-08-12 10:46:59,542 ERROR            Recording file path "MSGR_20220806_234707.wav" could not be made absolute since it is not in the recording directory "/Volumes/ABAIA/msgr-vesper-archive-starting-2021-nov-16/Recordings".
2022-08-12 10:46:59,542 INFO         Processing recording 2 of 2 - "MSGR / PC / start 2022-08-07 03:49:10+00:00 / duration 3.926 h"...
2022-08-12 10:46:59,544 INFO             Running detector on file "/Volumes/ABAIA/msgr-vesper-archive-starting-2021-nov-16/Recordings/MSGR_20220806_234910.wav"...
2022-08-12 10:47:00,645 INFO             BirdVoxDetect 0.6.0 FT 50 process completed abnormally with return code 1. No clips will be created.
2022-08-12 10:47:00,646 INFO             BirdVoxDetect 0.6.0 FT 50 process standard output was empty.
2022-08-12 10:47:00,646 INFO             BirdVoxDetect 0.6.0 FT 50 process standard error was:
2022-08-12 10:47:00,646 INFO                 /Users/richard/miniconda3/envs/birdvoxdetect-0.6.0/bin/python: Error while finding module specification for 'vesper_birdvox.run_birdvoxdetect' (ModuleNotFoundError: No module named 'vesper_birdvox')
2022-08-12 10:47:00,669 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/command/job_runner.py", line 144, in run_job
    complete = command.execute(info)
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/command/detect_command.py", line 146, in execute
    self._run_other_detectors(other_detectors, recordings)
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/command/detect_command.py", line 343, in _run_other_detectors
    self._run_other_detectors_on_file(
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/command/detect_command.py", line 433, in _run_other_detectors_on_file
    self._run_other_detectors_on_file_interval(
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/command/detect_command.py", line 467, in _run_other_detectors_on_file_interval
    detector.complete_detection()
  File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/vesper/birdvox/detectors.py", line 145, in complete_detection
    raise DetectorError(
vesper.birdvox.detectors.DetectorError: BirdVoxDetect 0.6.0 FT 50 process completed abnormally. See above log messages for details.


```

There's also a host of issues with cleaning up the files when running `pip install`, and I'm not sure why. 

```
/_libs/src/ujson/python/objToJSON.c -o build/temp.macosx-10.9-x86_64-3.9/pandas/_libs/src/ujson/python/objToJSON.o -D_GNU_SOURCE -Wno-unused-function
      pandas/_libs/src/ujson/python/objToJSON.c:181:12: error: use of undeclared identifier 'NUMPY_IMPORT_ARRAY_RETVAL'
          return NUMPY_IMPORT_ARRAY_RETVAL;
                 ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
  Running setup.py clean for pandas
  Building wheel for scikit-learn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      Partial import of sklearn during the build process.
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      accelerate_info:
        libraries accelerate not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
        libraries veclib not found in ['/Users/richard/miniconda3/envs/vesper-0.4.13/lib', '/usr/local/lib', '/usr/lib']
      Library veclib was not found. Ignoring
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/scikit-learn_0fcec67f10d64b2e9c39dab4224f00cb/setup.py", line 290, in <module>
          setup_package()
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/scikit-learn_0fcec67f10d64b2e9c39dab4224f00cb/setup.py", line 286, in setup_package
          setup(**metadata)
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/scikit-learn_0fcec67f10d64b2e9c39dab4224f00cb/setup.py", line 174, in configuration
          config.add_subpackage('sklearn')
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/setup.py", line 66, in configuration
          config.add_subpackage('utils')
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/utils/setup.py", line 8, in configuration
          from Cython import Tempita
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
  Building wheel for h5py (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-3.9
      creating build/lib.macosx-10.9-x86_64-3.9/h5py
      copying h5py/h5py_warnings.py -> build/lib.macosx-10.9-x86_64-3.9/h5py
      copying h5py/version.py -> build/lib.macosx-10.9-x86_64-3.9/h5py
      copying h5py/highlevel.py -> build/lib.macosx-10.9-x86_64-3.9/h5py
      copying h5py/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/h5py
      copying h5py/ipy_completer.py -> build/lib.macosx-10.9-x86_64-3.9/h5py
      creating build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/_hl
      creating build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_deprecation.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/common.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_threads.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests
      creating build/lib.macosx-10.9-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.macosx-10.9-x86_64-3.9/h5py/tests/test_vds
      running build_ext
      Loading library to get version: libhdf5.dylib
      error: dlopen(libhdf5.dylib, 0x0006): tried: '/Users/richard/miniconda3/envs/vesper-0.4.13/lib/libhdf5.dylib' (no such file), '/Users/richard/miniconda3/envs/vesper-0.4.13/lib/libhdf5.dylib' (no such file), '/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/lib-dynload/../../libhdf5.dylib' (no such file), '/Users/richard/miniconda3/envs/vesper-0.4.13/lib/libhdf5.dylib' (no such file), '/Users/richard/miniconda3/envs/vesper-0.4.13/bin/../lib/libhdf5.dylib' (no such file), 'libhdf5.dylib' (no such file), '/usr/local/lib/libhdf5.dylib' (no such file), '/usr/lib/libhdf5.dylib' (no such file), '/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/h5py_2cb6c2b14e8148f7bc02ebec9d834080/libhdf5.dylib' (no such file)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Running setup.py clean for h5py
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      /Users/richard/miniconda3/envs/vesper-0.4.13/bin/python /private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 168, in <module>
          main()
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 162, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Users/richard/miniconda3/envs/vesper-0.4.13/bin/python' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built numba
Failed to build numpy pandas scikit-learn h5py llvmlite
Installing collected packages: llvmlite, libclang, keras, audioread, tensorflow-io-gcs-filesystem, python-dateutil, pycparser, numpy, joblib, decorator, scipy, pandas, numba, h5py, cffi, soundfile, scikit-learn, resampy, PySoundFile, librosa, tensorflow, birdvoxclassify, birdvoxdetect, vesper_birdvox
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.0
    Uninstalling llvmlite-0.39.0:
      Successfully uninstalled llvmlite-0.39.0
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error

  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
      running build_ext
      /Users/richard/miniconda3/envs/vesper-0.4.13/bin/python /private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 168, in <module>
          main()
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 162, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/vp/bfx6rdf97lj71rj8720bb7qr0000gn/T/pip-install-85elopzn/llvmlite_7698c5e95d1a4628870320ab21c0ee7f/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Users/richard/miniconda3/envs/vesper-0.4.13/bin/python' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages
  Rolling back uninstall of llvmlite
  Moving to /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/llvmlite-0.39.0.dist-info/
   from /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/~lvmlite-0.39.0.dist-info
  Moving to /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/llvmlite/
   from /Users/richard/miniconda3/envs/vesper-0.4.13/lib/python3.9/site-packages/~lvmlite
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by HaroldMills** [comment]
It's not clear to me from the error messages what's going wrong. Please try deleting your birdvoxdetect-0.6.0 environment and reinstalling according to the instructions [here](https://vesper.readthedocs.io/en/latest/installation.html#installing-birdvoxdetect-optional). Note that the `vesper-birdvox` package is specified to pip with a dash in the name rather than an underscore.

**Comment by HaroldMills** [comment]
@RichardLitt, were you able to resolve this issue?

**Comment by RichardLitt** [comment]
Sorry, I've been traveling. I'll close this until I get back to my station and try again!

**Comment by HaroldMills** [comment]
Okay, thanks!
