### ISSUE TITLE
Unrecognized classifier

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#201]
Not sure why this one is coming up. Also, I've noticed that adding in an updated classifier (MPG 3.1) in the "Add Metadata" tab didn't help, here. 

```
[10/Aug/2022 18:05:07] "GET /jobs/75/ HTTP/1.1" 200 8693
2022-08-10 18:05:07,692 INFO     Job started for command "classify" with arguments:
2022-08-10 18:05:07,693 INFO         {
2022-08-10 18:05:07,694 INFO             "classifier": "MPG Ranch NFC Coarse Classifier 3.0",
2022-08-10 18:05:07,694 INFO             "annotation_name": "Classification",
2022-08-10 18:05:07,695 INFO             "station_mics": [
2022-08-10 18:05:07,696 INFO                 "MSGR / 21c"
2022-08-10 18:05:07,697 INFO             ],
2022-08-10 18:05:07,697 INFO             "start_date": "2022-08-01",
2022-08-10 18:05:07,698 INFO             "end_date": "2022-08-30",
2022-08-10 18:05:07,698 INFO             "detectors": [
2022-08-10 18:05:07,699 INFO                 "Old Bird Tseep Detector Redux 1.1"
2022-08-10 18:05:07,700 INFO             ],
2022-08-10 18:05:07,700 INFO             "tag": "-----"
2022-08-10 18:05:07,701 INFO         }
2022-08-10 18:05:08,266 ERROR    Classifier construction failed with an exception.
2022-08-10 18:05:08,267 ERROR    The exception message was:
2022-08-10 18:05:08,267 ERROR        Unrecognized classifier "MPG Ranch NFC Coarse Classifier 3.0".
2022-08-10 18:05:08,267 ERROR    The archive was not modified.
2022-08-10 18:05:08,275 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/classify_command.py", line 151, in _create_classifier
    cls = classes[name]
KeyError: 'MPG Ranch NFC Coarse Classifier 3.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/job_runner.py", line 144, in run_job
    complete = command.execute(info)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/classify_command.py", line 44, in execute
    classifier = self._create_classifier(job_info.job_id)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/classify_command.py", line 101, in _create_classifier
    e, 'Classifier construction', 'The archive was not modified.')
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/classify_command.py", line 97, in _create_classifier
    self._classifier_name, annotation_info, job, processor)
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/command/classify_command.py", line 153, in _create_classifier
    raise ValueError(f'Unrecognized classifier "{name}".')
ValueError: Unrecognized classifier "MPG Ranch NFC Coarse Classifier 3.0".
```

**Comment by RichardLitt** [comment]
Update: Adding in 3.1 worked once I restarted vesper in my terminal. Detections then worked only for 3.1, but not for 3.0. I am unable to remove classifiers in http://127.0.0.1:8000/admin, as far as I can tell.

**Comment by HaroldMills** [comment]
You should be able to remove the 3.0 classifier at http://127.0.0.1:8000/admin/vesper/processor/ (detectors and classifiers are collectively referred to as processors).

**Comment by RichardLitt** [comment]
Hmm! I waited a while and it worked - it may have just taken longer than I expected the first time. Thank you.
