### ISSUE TITLE
Migration froze

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#208]
Not sure why this would happen. As well, the error message suggesting a migration asks for a `python manage.py migrate` command, but there is no `manage.py` in the standard Archive Template. Not sure of a way around that. 

```sh
(vesper-0a53d06) ➜  nbnc-archive cp Archive\ Database.sqlite backup.sqlite
(vesper-0a53d06) ➜  nbnc-archive vesper_admin migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, vesper
Running migrations:
  Applying auth.0012_alter_user_first_name_max_length... OK

// HUNG here. I cancelled out. 

^CException ignored in: <module 'threading' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
^[[A%
(vesper-0a53d06) ➜  nbnc-archive vesper_admin migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, vesper
Running migrations:
  No migrations to apply.
  Your models in app(s): 'vesper' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
^CException ignored in: <module 'threading' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
(vesper-0a53d06) ➜  nbnc-archive vesper_admin makemigrations
Migrations for 'vesper':
  /Users/richard/Library/Python/3.7/lib/python/site-packages/vesper/django/app/migrations/0002_auto_20221023_1351.py
    - Alter field creating_job on annotationconstraint
    - Alter field creating_user on annotationconstraint
    - Alter field constraint on annotationinfo
    - Alter field creating_job on annotationinfo
    - Alter field creating_user on annotationinfo
    - Alter field creating_job on clip
    - Alter field creating_processor on clip
    - Alter field creating_user on clip
    - Alter field start_index on clip
    - Alter field creating_job on job
    - Alter field creating_user on job
    - Alter field end_time on job
    - Alter field processor on job
    - Alter field start_time on job
    - Alter field creating_job on recording
    - Alter field creating_job on stringannotation
    - Alter field creating_processor on stringannotation
    - Alter field creating_user on stringannotation
    - Alter field creating_job on stringannotationedit
    - Alter field creating_processor on stringannotationedit
    - Alter field creating_user on stringannotationedit
    - Alter field value on stringannotationedit
    - Alter field creating_job on tag
    - Alter field creating_processor on tag
    - Alter field creating_user on tag
    - Alter field creating_job on tagedit
    - Alter field creating_processor on tagedit
    - Alter field creating_user on tagedit
    - Alter field creating_job on taginfo
    - Alter field creating_user on taginfo
^CException ignored in: <module 'threading' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
(vesper-0a53d06) ➜  nbnc-archive        vesper_admin runserver
Watching for file changes with StatReloader
2022-10-23 14:00:23,364 INFO     Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): vesper.
Run 'python manage.py migrate' to apply them.
October 23, 2022 - 14:00:25
Django version 3.2.12, using settings 'vesper.django.project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C%
(vesper-0a53d06) ➜  nbnc-archive python manage.py migrate
python: can't open file '/Volumes/ABAIA/nbnc-archive/manage.py': [Errno 2] No such file or directory
(vesper-0a53d06) ➜  nbnc-archive vesper_admin migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, vesper
Running migrations:
  Applying vesper.0002_auto_20221023_1351... OK
/// Currently hanging here. Previously hanged

```

**Comment by HaroldMills** [comment]
I suspect this is due to the same underlying problem as #189, and I would suggest the same [workaround](https://vesper.readthedocs.io/en/latest/faq.html#i-ran-the-vesper-admin-command-and-it-hung-what-do-i-do). If you can confirm that the migration works for you in spite of the hang, I'll merge #189 and #208 into a new, more general issue. For what it's worth, I have looked into the issue some but have not yet found a solution.

`vesper_admin` is more or less a shorthand for `python manage.py`.

**Comment by RichardLitt** [comment]
I think it worked, in that there are no more warnings to migrate. However, I don't see the MPG or Birdvox detectors or classifiers, and running `conda activate vesper-0a53d06` or `conda activate vesper-0.4.12` runs Vesper 0.4.11a2, not the one requested, according to http://127.0.0.1:8000/about-vesper/. 

I think I missed a step in running the edge version in order to get the detectors, or http://127.0.0.1:8000/about-vesper/ isn't showing the right version. Can you help me figure this out?

**Comment by HaroldMills** [comment]
I will contact you via email about Vesper versions. I am closing this issue since it seems to be subsumed by #189 (which I just renamed).

**Comment by RichardLitt** [comment]
Sounds good. Thanks, @HaroldMills.
