### ISSUE TITLE
Issue importing recordings

### ISSUE THREAD

**Issue by lauren-grimes** [HaroldMills/Vesper#221]
I'm having an issue importing recordings. Full message:

2023-10-08 18:44:48,657 INFO     Job started for command "import" with arguments:
2023-10-08 18:44:48,657 INFO         {
2023-10-08 18:44:48,658 INFO             "importer": {
2023-10-08 18:44:48,658 INFO                 "name": "Recording Importer",
2023-10-08 18:44:48,658 INFO                 "arguments": {
2023-10-08 18:44:48,658 INFO                     "paths": [
2023-10-08 18:44:48,658 INFO                         "/Users/lauren/Desktop/Recordings"
2023-10-08 18:44:48,658 INFO                     ],
2023-10-08 18:44:48,659 INFO                     "recursive": false,
2023-10-08 18:44:48,659 INFO                     "recording_file_parser": {
2023-10-08 18:44:48,659 INFO                         "name": "MPG Ranch Recording File Parser",
2023-10-08 18:44:48,659 INFO                         "arguments": {
2023-10-08 18:44:48,659 INFO                             "station_name_aliases_preset": "Station Name Aliases"
2023-10-08 18:44:48,659 INFO                         }
2023-10-08 18:44:48,659 INFO                     }
2023-10-08 18:44:48,659 INFO                 }
2023-10-08 18:44:48,659 INFO             }
2023-10-08 18:44:48,659 INFO         }
2023-10-08 18:44:48,666 ERROR    Recording import failed with an exception.
The exception message was:
    Could not find recorder for recording file "/Users/lauren/Desktop/Recordings/XTH_2023-10-08_03.15.00_Z.wav".
The archive was not modified.
See below for exception traceback.
2023-10-08 18:44:48,670 ERROR    Job failed with an exception. See traceback below.
Traceback (most recent call last):
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/job_runner.py", line 144, in run_job
    complete = command.execute(info)
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/import_command.py", line 22, in execute
    return self._importer.execute(context)
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/recording_importer.py", line 58, in execute
    recordings = self._get_new_recordings()
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/recording_importer.py", line 81, in _get_new_recordings
    files = self._get_unimported_disk_files()
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/recording_importer.py", line 98, in _get_unimported_disk_files
    file = self._parse_recording_file(info.absolute_path)
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/recording_importer.py", line 212, in _parse_recording_file
    file.recorder = _get_recorder(file)
  File "/Users/lauren/miniconda3/envs/vesper-0.4.14/lib/python3.10/site-packages/vesper/command/recording_importer.py", line 355, in _get_recorder
    raise CommandExecutionError(
vesper.command.command.CommandExecutionError: Could not find recorder for recording file "/Users/lauren/Desktop/Recordings/XTH_2023-10-08_03.15.00_Z.wav".

**Comment by lauren-grimes** [comment]
nevermind, I was able to fix this! I had to change the start time for my devices to 10-07 rather than 10-08.

**Comment by HaroldMills** [comment]
Great: glad you were able to figure this out!
