### ISSUE TITLE
Incremental archiving fails when file "ClipDatabase.db new" already exists.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#23]
In order to accelerate database operations, the archiver operates on an in-memory copy of the clips database, which it writes out to disk at the end of its operation. So that the original database file `ClipDatabase.db` remains if something goes wrong with the write, the new database is first written to a file called `ClipDatabase.db new`, and then the old database is deleted and the new one renamed to `ClipDatabase.db` if and only if the write succeeds.

Bill Evans uncovered a problem with this scheme. Somehow he wound up with both `ClipDatabase.db` and `ClipDatabase.db new` in an archive instead of just `ClipDatabase.db`, and when he tried to archive a new day's data incrementally the creation of the new database failed. Here is a stack trace of the error:

```
Traceback (most recent call last):
  File "/Users/Harold/Documents/Code/Python/NFC/scripts/nfc_archiver.py", line 1238, in <module>
_main()
  File "/Users/Harold/Documents/Code/Python/NFC/scripts/nfc_archiver.py", line 140, in _main
_close_archive(archive, logger)
  File "/Users/Harold/Documents/Code/Python/NFC/scripts/nfc_archiver.py", line 363, in _close_archive
archive.close()
  File "/Users/Harold/Documents/Code/Python/NFC/src/nfc/archive/archive.py", line 187, in close
self._close_db()
  File "/Users/Harold/Documents/Code/Python/NFC/src/nfc/archive/archive.py", line 198, in _close_db
_copy_db(self._conn, file_conn)
  File "/Users/Harold/Documents/Code/Python/NFC/src/nfc/archive/archive.py", line 750, in _copy_db
_create_db_tables(to_conn)
  File "/Users/Harold/Documents/Code/Python/NFC/src/nfc/archive/archive.py", line 794, in _create_db_tables
    cursor.execute(_CREATE_STATION_TABLE_SQL)
sqlite3.OperationalError: table Station already exists
```

Two points about this:
- Normally the `ClipDatabase.db new` file would have been deleted by the previous archiving operation, so presumably something went wrong with it. We should try to ensure that when something goes wrong we provide an informative error message to the user and recover more gracefully.
- In the `_close_db` method we should test whether `ClipDatabase.db new` exists before we open it and behave more gracefully if it does.

**Comment by HaroldMills** [comment]
Closed this and a bunch of other issues that have become outdated as Vesper transitions from a desktop app to a web app.
