### ISSUE TITLE
MPG Ranch bat importer fails for station aliases not included in hard-coded mapping.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#84]
Debbie Leick tried to run the MPG Ranch bat importer on some data and got the stack trace at the end of this note (Debbie sent the stack trace to me in an email message on 2016-12-07). The KeyError was raised because the station alias "sage-sc" is not in the `_STATION_NAMES` mapping of the `vesper.mpg_ranch.bat_importer` module. Such an exception is not necessarily a problem: it should happen whenever a station name that appears in a file name does not match any station name that appears in the archive database (after both are converted to lower case). The second exception *is* a problem, however, and occurs because the `BatImporter.import_` method attempts to access the `_capitalized_station_names` attribute of a `BatImporter` before the attribute has been initialized. The attempted access occurs in the first line of the `import_` method, which initializes the `_classifications` attribute. This initialization should be moved so that it occurs after the initialization of the `_capitalized_station_names` attribute, a few lines down in the same method.

The stack trace:

C:\Users\dleick>vcl import "MPG Ranch Bat Importer" --input-dir "K:\bwi_interns\grace_bat_data\sage_sc\vesper_import" --archive "C:\Users\dleick\Test_bat_archive"
Traceback (most recent call last):
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 285, in _parse_station_name
    return _STATION_NAMES[name]
KeyError: 'sage-sc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dleick\Miniconda3\Scripts\vcl-script.py", line 5, in <module>
    sys.exit(vesper.vcl.vcl.main())
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\vcl\vcl.py", line 122, in main
    success = command.execute()
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\vcl\import_command.py", line 27, in execute
    return self._delegate.import_()
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 120, in import_
    self._classifications = self._get_classifications(self._input_dir_path)
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 151, in _get_classifications
    return dict(self._get_classification(*t) for t in df.itertuples())
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 151, in <genexpr>
    return dict(self._get_classification(*t) for t in df.itertuples())
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 155, in _get_classification
    station_name, start_time = self._parse_file_name_base(file_name_base)
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 273, in _parse_file_name_base
    station_name = self._parse_station_name(station_name_parts)
  File "C:\Users\dleick\Miniconda3\lib\site-packages\vesper\mpg_ranch\bat_importer.py", line 288, in _parse_station_name
    return self._capitalized_station_names[name]
AttributeError: 'BatImporter' object has no attribute '_capitalized_station_names'

**Comment by HaroldMills** [comment]
This issue pertains to the desktop version of Vesper, which is no longer being developed, so I am closing it.
